Mirantis/k8s-AppController

- README.md
> Updated README with documentation of basic concepts

- appcontroller.yaml
Delete temporary env workaround
> Change docker image to mirantis/k8s-appcontroller

- cmd/kubeac/main.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
> Cycle detection

- cmd/kubeac/main.go
- scheduler/scheduler.go
> Allow limiting number of concurrently creating resources

- cmd/kubeac/main.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
> Stop using pointer for scheduler.DependencyGraph

- scheduler/scheduler.go
> Create resources based on dependency list

- cmd/kubeac/main.go
- scheduler/scheduler.go
> Limit concurrency

- README.md
- client/client.go
- client/dependencies.go
- client/resdef.go
- examples/extended/create.sh
- examples/extended/delete.sh
- examples/extended/deps.yaml
- examples/extended/replicaset.yaml
- mocks/client.go
- mocks/countingresource.go
- mocks/dependencies.go
- mocks/replicasets.go
- mocks/resdefs.go
- resources/job.go
- resources/pod.go
- resources/replicaset.go
- resources/replicaset_test.go
- resources/service.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
As in description. This PR tries to fulfill #19 
Things to do:
> Provide replicaset resource type.

- scheduler/scheduler.go
> Fix golint hinted minor isssue.

- examples/extended/create.sh
- examples/extended/deps.yaml
- examples/extended/pod9.yaml
- examples/extended/service.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/57)
> Community demo extended example

- examples/services/create.sh
- examples/services/deps.yaml
- examples/services/job.yaml
- examples/services/pod.yaml
- examples/services/pod2.yaml
- examples/services/pod3.yaml
- examples/services/pod4.yaml
- examples/services/service.yaml
- manifests/appcontroller.yaml
- mocks/jobs.go
- mocks/pods.go
- mocks/replicasets.go
- mocks/services.go
- resources/common.go
- resources/service.go
- resources/service_test.go
- scheduler/scheduler.go
It's done. Please review
fixes #17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/52)
> Service status check checks underlying objects status

- client/client.go
- client/resdef.go
- examples/extended/create.sh
- examples/extended/deps.yaml
- examples/extended/petset.yaml
- mocks/client.go
- mocks/petsets.go
- mocks/resdefs.go
- resources/common.go
- resources/petset.go
- resources/petset_test.go
- resources/replicaset.go
- resources/service.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
Extended client, scheduler, resources modules to support PetSets
Added test for creating dependency graph with all supported resources
Added PetSet mocks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/68)
> PetSet support

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/70)
> kubernetes community meeting link demo in README

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/69)
> petsets in readme

- README.md
Please add this nice badge showing our progress
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/72)
> Added waffle badge, closes #71

- README.md
- client/client.go
- client/resdef.go
- examples/extended/create.sh
- examples/extended/daemonset.yaml
- examples/extended/delete.sh
- examples/extended/deps.yaml
- mocks/client.go
- mocks/daemonsets.go
- mocks/resdefs.go
- resources/daemonset.go
- resources/daemonset_test.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/67)
> Daemonset support

- README.md
Small one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/84)
> Fix README for single binary

- tests/README.md
- tests/linear/definitions.yaml
- tests/linear/dependencies.yaml
- tests/linear/expected_order.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/66)
> Linear test case

- cmd/cmd.go
- cmd/deploy.go
- cmd/deploy_test.go
Slight refactor of deploy command to make it testable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/89)
> Label selector retrieval tests

- docs/research/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/97)
> Added initial README to docs/research

- docs/research/failure-handling.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/98)
> Failure Handling research

- docs/research/failure-handling.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/99)
> More correct naming for ignore all

- cmd/bootstrap.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/103)
> Make bootstrap client secure again

- docs/research/daemonset-dependencies.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/100)
> DS->DS dependency research

- docs/research/lcm.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/101)
> lcm research

- utils/graph-builder/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/113)
> Fixed title in graph builder

- client/client.go
- client/resdef.go
- examples/extended/configmap1.yaml
- examples/extended/create.sh
- examples/extended/deps.yaml
- mocks/client.go
- mocks/configmaps.go
- mocks/resdefs.go
- resources/common.go
- resources/configmap.go
- resources/configmap_test.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
Closes #109
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/107)
> Initial support for ConfigMaps

- Dockerfile
- hooks/pre_build
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/115)
> Use dockerhub hooks to make final image smaller

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/120)
> Corrected path to manifests in Dockerfile

- glide.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/123)
> Pinned versions in glide.yaml

- client/client.go
- client/resdef.go
- examples/extended/create.sh
- examples/extended/delete.sh
- examples/extended/deps.yaml
- examples/extended/secrets.yaml
- mocks/client.go
- mocks/resdefs.go
- mocks/secrets.go
- resources/common.go
- resources/secrets.go
- resources/secrets_test.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
closes #110 
It's pretty much the same code as #107 just changed `ConfigMap` to `Secret` etc. (including @nebril  test stuff)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/114)
> Support for secrets

- resources/daemonset.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/127)
> Remove obsolete method from daemonset

- client/client.go
- client/resdef.go
- examples/extended/create.sh
- examples/extended/deployment.yaml
- examples/extended/deps.yaml
- mocks/client.go
- mocks/deployment.go
- mocks/resdefs.go
- resources/common.go
- resources/deployment.go
- resources/deployment_test.go
- resources/replicaset.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
fixes #94
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/122)
> Deployment support

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/131)
> Adjusted makefile to recent changes

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/129)
> Add all resources to readme

- resources/common.go
- resources/configmap.go
- resources/daemonset.go
- resources/job.go
- resources/petset.go
- resources/pod.go
- resources/replicaset.go
- resources/secrets.go
- resources/service.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/128)
> Refactor some duplicated code

- .codeclimate.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/132)
> disabled GoLint/Comments/DocComments

- client/resdef.go
- scheduler/scheduler.go
This is the first part of refactorings to allow failure handling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/125)
> Failure handling related refactoring

- resources/configmap.go
- resources/daemonset.go
- resources/deployment.go
- resources/job.go
- resources/petset.go
- resources/pod.go
- resources/replicaset.go
- resources/secrets.go
- resources/service.go
Fixes #137 
Fixes #138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/141)
> Remove resources.XXX from resources.ExistingXXX

- mocks/configmaps.go
- mocks/secrets.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/140)
> Fix 2 minor golint issues

- README.md
Fixes #136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/139)
> Recommend running pod from remote manifest

- examples/extended/delete.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/144)
> Fix extended examples cleanup

- cmd/get-status.go
- interfaces/interfaces.go
- mocks/countingresource.go
- mocks/resource.go
- report/report.go
- resources/configmap.go
- resources/daemonset.go
- resources/deployment.go
- resources/job.go
- resources/petset.go
- resources/pod.go
- resources/replicaset.go
- resources/secrets.go
- resources/service.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
Improved get-status to yield more data. Needs some smoke-testing and
presentation, but the logic can be reviewed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/105)
> Improved get-status

- interfaces/interfaces.go
- mocks/countingresource.go
- mocks/resource.go
- report/report.go
- resources/common.go
- resources/configmap.go
- resources/daemonset.go
- resources/deployment.go
- resources/job.go
- resources/petset.go
- resources/pod.go
- resources/replicaset.go
- resources/secrets.go
- resources/service.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/146)
> Rename resource interfaces to better reflect their meaning

- client/client.go
- mocks/client.go
- mocks/counterwithmemo.go
- mocks/countingresource.go
- mocks/daemonsets.go
- mocks/deployment.go
- mocks/jobs.go
- mocks/petsets.go
- mocks/pods.go
- mocks/replicasets.go
- mocks/resource.go
- mocks/services.go
- resources/daemonset.go
- resources/daemonset_test.go
- resources/deployment.go
- resources/petset.go
- resources/service.go
- resources/service_test.go
- scheduler/scheduler.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/148)
> Add space after // in comments

- interfaces/interfaces.go
- mocks/countingresource.go
- mocks/resource.go
- resources/common.go
- resources/configmap.go
- resources/daemonset.go
- resources/deployment.go
- resources/job.go
- resources/petset.go
- resources/pod.go
- resources/replicaset.go
- resources/secrets.go
- resources/service.go
- scheduler/scheduler.go
Partially addresses #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/142)
> Failure handling: add metadata to resource

- glide.lock
Autogenerated after glide update `--strip-vendor`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/149)
> Updated glide.lock

- README.md
- cmd/get-status.go
- glide.yaml
- human/human.go
- interfaces/interfaces.go
- report/report.go
You can now read a detailed report of the deployment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/151)
>  Added human-readable report of deployment 

- client/client.go
- client/resdef.go
- examples/extended/create.sh
- examples/extended/delete.sh
- examples/extended/deps.yaml
- examples/extended/pvc.yaml
- mocks/client.go
- mocks/persistentvolumeclaims.go
- mocks/resdefs.go
- resources/common.go
- resources/configmap.go
- resources/persistentvolumeclaim.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
Also fixed a bug in which configmap keys started with configMap instead
of configmap.
fixes #135 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/153)
> PersistentVolumeClaim support

- .gitignore
- examples/common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/154)
> Rework logic in common.sh and add kubeac to gitignore

- manifests/appcontroller.yaml
- scripts/import.sh
Speed ups e2e example testing for those who are using dind cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/157)
> Add helpers to import docker image for dind users

- client/client.go
- mocks/client.go
- mocks/configmaps.go
- mocks/daemonsets.go
- mocks/deployment.go
- mocks/jobs.go
- mocks/persistentvolumeclaims.go
- mocks/pods.go
- mocks/replicasets.go
- mocks/secrets.go
- mocks/services.go
- mocks/statefulsets.go
- resources/configmap_test.go
- resources/daemonset_test.go
- resources/deployment_test.go
- resources/replicaset_test.go
- resources/secrets_test.go
- resources/service_test.go
- resources/statefulset_test.go
- scheduler/scheduler_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/160)
> Use fake clientset instead of mocks

- examples/common.sh
- examples/extended/create.sh
- examples/services/create.sh
- examples/simple/create.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/158)
> Wait until k8s-appcontroller pod is running and resources registered

- pkg/resources/common.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/166)
> Improve logging message for not found existing res

- examples/extended/delete.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/164)
> Fix extended example cleanup

- README.md
Short roadmap that matches one discussed on sig-apps yesterday.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/170)
> Added short roadmap to README.md

- scripts/import.sh
If MASTER_NAME is set but empty it will *not* import on master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/176)
> Added conditional master import

- scripts/checkout_k8s.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/178)
> Fixed invalid syntax in checkout_k8s.sh

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/183)
> Ignore error from rmi in makefile

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/185)
> Add Go Report badge to README

- Makefile
- scripts/dind_down.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/193)
> Add dind down to make clean-k8s

- examples/on-error-subgraph/create.sh
- examples/on-error-subgraph/delete.sh
- examples/on-error-subgraph/deps.yaml
- examples/on-error-subgraph/pod.yaml
- examples/on-error-subgraph/pod2.yaml
- pkg/resources/common.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/184)
> Add 'on-error' subgraph

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/195)
> Remove e2e binary on cleanup

- e2e/basic_test.go
- e2e/utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/196)
> Add e2e test for on-error subgraph

- examples/extended/create.sh
- examples/extended/delete.sh
- examples/extended/serviceaccount.yaml
- pkg/client/client.go
- pkg/client/resdef.go
- pkg/mocks/resdefs.go
- pkg/mocks/serviceaccounts.go
- pkg/resources/common.go
- pkg/resources/serviceaccount.go
- pkg/resources/serviceaccount_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
closes #133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/197)
> Added service account

- e2e/basic_test.go
- e2e/utils/utils.go
- pkg/client/client.go
- pkg/client/dependencies.go
- pkg/client/resdef.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/200)
> ThirdPartyResource clients use AC namespace

- pkg/interfaces/interfaces.go
- pkg/mocks/countingresource.go
- pkg/mocks/resource.go
- pkg/resources/common.go
- pkg/resources/replicaset.go
- pkg/resources/replicaset_test.go
- pkg/resources/service.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Implement smarter status & error caching -- required by future improvements incl. timeouts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/201)
> Rework status

- e2e/basic_test.go
- examples/timeout/create.sh
- examples/timeout/delete.sh
- examples/timeout/deps.yaml
- examples/timeout/pod.yaml
- examples/timeout/pod2.yaml
- examples/timeout/timedout-pod.yaml
- pkg/resources/pod.go
- pkg/scheduler/scheduler.go
Partially addresses #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/199)
> Failure handling: timeout

- e2e/basic_test.go
- examples/on-error-ignore/create.sh
- examples/on-error-ignore/delete.sh
- examples/on-error-ignore/deps.yaml
- examples/on-error-ignore/pod.yaml
- examples/on-error-ignore/timedout-pod.yaml
- pkg/resources/common.go
- pkg/scheduler/scheduler.go
Partially implements #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/205)
> Implement 'on error - ignore this'

- cmd/get-status.go
- pkg/report/report.go
- pkg/resources/daemonset.go
- pkg/resources/daemonset_test.go
- pkg/resources/deployment.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/208)
> Add missing license headers

- cmd/deploy.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Use channel to terminate deployment workflow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/211)
> Use channel to terminate deployment workflow

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/215)
> Updated roadmap in readme

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/216)
> Bump k8s on CI to 1.5.4 and 1.4.9

- Dockerfile
- ac-run.sh
- ac-stop.sh
- ac_service.sh
- run_runit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/226)
> Remove all runit related scripts

- cmd/deploy.go
- cmd/get-status.go
- e2e/example_runner.go
- pkg/client/flows.go
- pkg/client/resdef.go
- pkg/interfaces/interfaces.go
- pkg/resources/common.go
- pkg/resources/flow.go
- pkg/scheduler/dependency_graph.go
- pkg/scheduler/scheduler_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/222)
> Basic flow capabilities

- cmd/bootstrap.go
- cmd/deploy.go
- cmd/format/format.go
- manifests/replicas.json
- pkg/client/client.go
- pkg/client/flows.go
- pkg/interfaces/interfaces.go
- pkg/mocks/client.go
- pkg/mocks/fake_dependencies.go
- pkg/mocks/fake_replicas.go
- pkg/resources/flow.go
- pkg/scheduler/dependency_graph.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Now it is possible to delete resources created by flow replica
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/234)
> Flows destruction

- cmd/get-status.go
- cmd/run.go
- e2e/example_runner.go
- e2e/examples_test.go
- e2e/flows_test.go
- e2e/utils/appcmanager.go
- examples/flows/create.sh
- examples/flows/deps.yaml
- examples/flows/flow.yaml
- examples/flows/job.yaml
- examples/flows/job2.yaml
- examples/flows/pod.yaml
- examples/flows/pod2.yaml
- pkg/client/client.go
- pkg/resources/common.go
- pkg/resources/configmap.go
- pkg/resources/daemonset.go
- pkg/resources/deployment.go
- pkg/resources/flow.go
- pkg/resources/job.go
- pkg/resources/persistentvolumeclaim.go
- pkg/resources/petset.go
- pkg/resources/pod.go
- pkg/resources/replicaset.go
- pkg/resources/secrets.go
- pkg/resources/service.go
- pkg/resources/serviceaccount.go
- pkg/resources/statefulset.go
- pkg/scheduler/frontend.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/244)
> Flows e2e tests

- e2e/flows_test.go
- pkg/interfaces/interfaces.go
- pkg/resources/flow.go
- pkg/scheduler/dependency_analyzer.go
- pkg/scheduler/dependency_graph.go
- pkg/scheduler/flows_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
$AC_NAME was not evaluated for dependency arg values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/253)
> Fixes $AC_NAME evaluation in dependency args

- README.md
- docs/flows.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/256)
> Flows documentation

- docs/flows.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/260)
> Minor whitespace and typo fixes in flow docs

- .codeclimate.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/263)
> Enabled doc checks in golint
