Mirantis/k8s-AppController

Dockerfile
client/client.go
cmd/bootstrap/main.go
examples/extended/create.sh
examples/simple/create.sh
manifests/appcontroller.yaml
manifests/dependencies.json
manifests/dependencies.yaml
manifests/resdefs.json
manifests/resdefs.yaml

The command is a go binary, which creates ThirdPartyResources.
It is added to AppController image.
AppController pod is given initcontainer which runs the binary.
ThirdPartyResource manifests moved to json files due to unmarshalling
problems
If the ThirdPartyResources already exist in cluster - don't do anything

Bootstrap command for creating ThirdPartyResources

---

Dockerfile

Remove /go after everything is build. It saves more than 800MB on image size.

Remove /go directory to save some space (~800MB)

---

Dockerfile
manifests/appcontroller.yaml

Other possibility would be to use `/usr/share/kubeac`, but `/opt` seems also ok for things distributed in binary form.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/60)

Use more standard directories.

---

cmd/wrap/format/format.go
cmd/wrap/format/json.go
cmd/wrap/format/json_test.go
cmd/wrap/format/yaml.go
cmd/wrap/format/yaml_test.go
cmd/wrap/main.go
cmd/wrap/main_test.go

This PR provides a small refactor in `wrap` command.
File format is extracted into separate package/interface.
Added `json` as file format.
`yaml` as default format (no changed behavior in usage).
Additional error checking on missing `name` required parameter.
Fixes #61 
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/62)

wrap: Refactor and provide JSON format

---

cmd/wrap/format/format.go
cmd/wrap/format/json.go
cmd/wrap/format/json_test.go
cmd/wrap/format/yaml.go
cmd/wrap/format/yaml_test.go
cmd/wrap/main.go

Yaml format supportis multi-document files ("---" delimited)
fixes #73 #75 (#73 makes sense only for yaml files, since json doesn't support multi-document files).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/76)

Wrapped resource doesn't need name from user

---

cmd/bootstrap.go

While dialing the cluster other errors than StatusError can happen (e.g.
url.Error). These errors caused panic without getting logged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/86)

Corrected error handling

---

README.md
cmd/cmd.go
cmd/deploy.go
manifests/appcontroller.yaml

AppController pod has APPCONTROLLER_LABEL_SELECTOR env variable, which
holds the selector to be used in Dependencies and Definitions retrieval.
`labels` flag for `kubeac deploy` is retained for testing purposes.
fixes #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/88)

AppController selectors are defined on pod creation

---

README.md
cmd/deploy.go
cmd/deploy_test.go
manifests/appcontroller.yaml

Addresses #91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/92)

Set envvars naming to KUBERNETES_AC_{something} pattern

---

cmd/cmd.go
cmd/get-status.go
resources/common.go
scheduler/scheduler.go
scheduler/scheduler_test.go

The 'get-status' command would print the information about the status of
deployment.
fixes #78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/90)

Added get-status command

---

README.md
client/client.go
client/dependencies.go
client/mocks/definitions.json
client/mocks/dependencies.json
client/mocks/dependency.json
client/mocks/job-definition.json
client/mocks/pod-definition.json
client/resdef.go
cmd/bootstrap.go
cmd/format/json.go
cmd/format/json_test.go
cmd/format/yaml.go
cmd/format/yaml_test.go
examples/extended/deps.yaml
examples/services/deps.yaml
examples/simple/deps.yaml
manifests/dependencies.json
manifests/resdefs.json
tests/linear/definitions.yaml
tests/linear/dependencies.yaml
utils/graph-builder/index.html

fixes #25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/29)

Unify k8s api endpoints

---

docs/research/failure-handling.md

Corrected "childer" to "children" (typo from previous PR, and changed "this" to current to better reflect the naming
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/102)

Corrected typo and changed "this" to "current"

---

interfaces/interfaces.go
mocks/countingresource.go
mocks/resource.go
resources/common.go
resources/daemonset.go
resources/job.go
resources/petset.go
resources/pod.go
resources/replicaset.go
resources/service.go
scheduler/scheduler.go

- got rid of newResourceFor* functions in scheduler
- got rid of switching by `kind` in scheduler
- extracted Resource interface to new package `interfaces` (this is
because tests are in a package they are testing, which resulted in
circular imports between `resources` and `mocks` packages)
- expanded Resource interface with methods for matching the name of
resource definition and creating new objects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/104)

Refactor for ease of adding new resource types

---

interfaces/interfaces.go
mocks/countingresource.go
mocks/resource.go
resources/daemonset.go
resources/job.go
resources/petset.go
resources/pod.go
resources/replicaset.go
resources/service.go

Delete method would be needed as a part of some failure handling scenarios, like 'cleanup on failure' 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/108)

Add Delete method to Resource

---

interfaces/interfaces.go
resources/common.go
scheduler/scheduler.go

No new functionality. Just some design beautification. Like 'I' in 'SOLID
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/111)

Extract Resource creation methods into separate interface

---

client/client.go
manifests/appcontroller.yaml

fixes #95 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/112)

All clients are set to use AC pod namespace

---

hooks/pre_build

* Added echo (`-x`) to pre_build
* Checking for vendor directory, will *not* execute glide install when found.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/118)

Improved pre_build script

---

glide.lock

Pinned temporary k8s to 1.4.6 (instead of 1.5.0 alpha-something)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/119)

Pin k8s to 1.4.6

---

examples/common.sh
examples/extended/create.sh
examples/extended/delete.sh
examples/services/create.sh
examples/simple/create.sh

You can override it by manually exporting `KUBECTL_NAME`. The problem is simple, sometimes you need kubectl.sh sometimes you want kubectl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/124)

Detect name of kubectl (kubectl vs kubectl.sh)

---

examples/common.sh
examples/extended/create.sh
examples/extended/deps.yaml

Removed PersistentVolumeClaim from example due to it not being able to
become ready on clusters without provisioned PersistentVolume
Added kubectl.sh as possible kubectl name in common.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/162)

Fix extended example

---

scripts/import.sh

uses save/load combo instead import/export, also changed default names to match kubeadm-dind-cluster (possible to change using ENV variables).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/175)

Improve import.sh script

---

README.md

It was already outdated. It makes kinda no sense to keep it in that form.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/177)

Remove list of k8s objects from Readme

---

pkg/client/client.go
pkg/mocks/client.go
pkg/resources/statefulset_test.go

Fixed shadowing that were preventing client from correctly reporting
what API version is enabled/disabled.
Added unit test to verify disabled state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/187)

Fix shadowing in client.IsEnabled

---

Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/191)

Do not fail on clean when no .k8s-cluster found

---

.travis.yml
Makefile
scripts/docker_publish.sh

After this patch we will publish docker images after selected succesfull builds.
We are running builds both for kubernetes 1.5.2/go1.7 and kubernetes 1.4.8/go1.6
and publish script will be executed after any succesfull build. To avoid ambiguity we will enable
publishing only for build with go1.7.
We will publish image in next cases:
- After build will pass on master branch, we will publish image with tag - latest
- After build will pass on tagged commit, we will publish image with specified tag
- After build will pass on any other branch, we will publish image with name of that branch
We won't be publishing images for each PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-ap …

Publish to docker after succesfull build

---

cmd/cmd.go

before
```
Usage:
ac [command]
Available Commands:
bootstrap   Bootstrap AppController
get-status  Get status of deployment
run         Start deployment of AppController graph
wrap        Echo wrapped k8s object to stdout
```
now
```
Usage:
kubeac [command]
Available Commands:
bootstrap   Bootstrap AppController
get-status  Get status of deployment
run         Start deployment of AppController graph
wrap        Echo wrapped k8s object to stdout
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/198)

Change cmd help name from ac to kubeac

---

e2e/basic_test.go
examples/on-error-ignore-all/create.sh
examples/on-error-ignore-all/delete.sh
examples/on-error-ignore-all/deps.yaml
examples/on-error-ignore-all/pod.yaml
examples/on-error-ignore-all/pod2.yaml
examples/on-error-ignore-all/timedout-pod.yaml
pkg/mocks/resource.go
pkg/resources/common.go
pkg/resources/common_test.go
pkg/scheduler/scheduler.go

Partially addresses #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/207)

Implement 'on-error - ignore-all'

---

pkg/interfaces/interfaces.go
pkg/mocks/countingresource.go
pkg/mocks/resource.go
pkg/report/report.go
pkg/resources/common.go
pkg/resources/configmap.go
pkg/resources/configmap_test.go
pkg/resources/daemonset.go
pkg/resources/daemonset_test.go
pkg/resources/deployment.go
pkg/resources/deployment_test.go
pkg/resources/job.go
pkg/resources/persistentvolumeclaim.go
pkg/resources/petset.go
pkg/resources/pod.go
pkg/resources/replicaset.go
pkg/resources/replicaset_test.go
pkg/resources/secrets.go
pkg/resources/secrets_test.go
pkg/resources/service.go
pkg/resources/service_test.go
pkg/resources/serviceaccount.go
pkg/resources/serviceaccount_test.go
pkg/resources/statefulset.go
pkg/resources/statefulset_test.go
pkg/scheduler/scheduler.go

ResourceStatus is a new type based on string with 3 const values which are
used for setting resource status.
fixes #126 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/206)

Use ResourceStatus type instead of string

---

README.md
cmd/deploy.go
cmd/deploy_test.go
cmd/get-status.go
e2e/basic_test.go
e2e/utils/appcmanager.go
examples/extended/create.sh
examples/extended/delete.sh
examples/on-error-subgraph/delete.sh
examples/services/create.sh
examples/simple/create.sh
examples/timeout/create.sh
examples/timeout/delete.sh
manifests/appcontroller.yaml
manifests/cfg.yaml
pkg/scheduler/controller.go
pkg/scheduler/controller_test.go

Instead of running ac-run inside of the appcontroller pod user will
have to create documented config map with several fields (concurrency, labels selector).
appcontroller process will listen to changes for that config map and run deployment graph
processing, on deletion of configmap we will terminate deployment workflow.
It will allow us to provide guarantees that workflow will be finished even if appcontroller
pod will crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/214)

Refactor appcontroller to work as long running controller

---

.travis.yml
scripts/docker_publish.sh
scripts/import.sh

- Add copyright notices
- Currently, CI pushing images only with latest tag:
https://travis-ci.org/Mirantis/k8s-AppController/jobs/203410745#L1998-L2001
No one paid attention to this, because the "after_success" step failure
doesn't fail build:
https://github.com/travis-ci/travis-ci/issues/758
And at the moment a good fix is to use this as the last entry of
"script" step instead of "after_success" step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/228)

Fixed docker publish

---

cmd/deploy.go
cmd/get-status.go
e2e/example_runner.go
pkg/client/flows.go
pkg/client/resdef.go
pkg/interfaces/interfaces.go
pkg/resources/common.go
pkg/resources/flow.go
pkg/scheduler/dependency_graph.go
pkg/scheduler/scheduler_test.go

* Ability to specify flow as exported (exported: true)
* If the flow is exported it can be deployed with "kubeac run flowName"
* BuildDependencyGraph arguments were refactored into structure.
The value provided is also accessible by resource classes via GraphContext
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/223)

Exportable flows 

---

cmd/deploy.go
cmd/format/format.go
cmd/format/json.go
cmd/format/yaml.go
cmd/get-status.go
e2e/example_runner.go
pkg/client/client.go
pkg/client/dependencies.go
pkg/client/flows.go
pkg/copier/copier.go
pkg/interfaces/interfaces.go
pkg/resources/common.go
pkg/resources/configmap.go
pkg/resources/daemonset.go
pkg/resources/deployment.go
pkg/resources/flow.go
pkg/resources/job.go
pkg/resources/persistentvolumeclaim.go
pkg/resources/petset.go
pkg/resources/pod.go
pkg/resources/replicaset.go
pkg/resources/secrets.go
pkg/resources/service.go
pkg/resources/serviceaccount.go
pkg/resources/statefulset.go
pkg/scheduler/dependency_graph.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

* It is possible to declare parameters of the flows with description and default value
* Argument values can be used anywhere in the resource definitions except for the container parts
(not to cause conflicts with shell variables)
* Dependencies can carry arguments between resources (for example, to map self arguments to parameters
of the flow being triggered)
* It is possible to have several dependencies on the same object with different arguments. If the argument is
used as part of the resource name it will produce different resource for each such dependency despite
both parent and child being the same
* Arguments can be specified in the command line (kubeac run myFlow --arg arg1=value1, --arg arg2: value2
Argument are validated: undeclared arguments are not allowed (unless there is a …

Dependency graph parametrization

---

cmd/bootstrap.go
cmd/deploy.go
cmd/format/format.go
manifests/replicas.json
pkg/client/client.go
pkg/client/flows.go
pkg/interfaces/interfaces.go
pkg/mocks/client.go
pkg/mocks/fake_dependencies.go
pkg/mocks/fake_replicas.go
pkg/scheduler/dependency_graph.go
pkg/scheduler/scheduler_test.go

Flows can now be replicated. Each flow replica gets a unique name
which is available through the $AC_NAME variable.
In order for a replica to get the same name on each run, new
FlowDeployment (Deployment.appcontroller.k8s) TPR is created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/230)

Replication of flows

---

cmd/get-status.go
cmd/run.go
e2e/example_runner.go
pkg/client/client.go
pkg/resources/common.go
pkg/resources/configmap.go
pkg/resources/daemonset.go
pkg/resources/deployment.go
pkg/resources/flow.go
pkg/resources/job.go
pkg/resources/persistentvolumeclaim.go
pkg/resources/petset.go
pkg/resources/pod.go
pkg/resources/replicaset.go
pkg/resources/secrets.go
pkg/resources/service.go
pkg/resources/serviceaccount.go
pkg/resources/statefulset.go
pkg/scheduler/frontend.go

1) get-status command was missing ability to specify flow name and
flow args
2) flow Status() method used to return status based on whether flow
is running or not rather than on statuses of resources in that flow.
This didn't work with get-status command which doesn't run anything.
Now the flow status is obtained from the entire subgraph status
3) Helper method to get deployment status was written that can be used
from both get-status CLI and e2e tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/242)

get-status improvements

---

cmd/get-status.go
cmd/run.go
e2e/example_runner.go
e2e/examples_test.go
e2e/utils/appcmanager.go
pkg/client/client.go
pkg/resources/common.go
pkg/resources/configmap.go
pkg/resources/daemonset.go
pkg/resources/deployment.go
pkg/resources/flow.go
pkg/resources/job.go
pkg/resources/persistentvolumeclaim.go
pkg/resources/petset.go
pkg/resources/pod.go
pkg/resources/replicaset.go
pkg/resources/secrets.go
pkg/resources/service.go
pkg/resources/serviceaccount.go
pkg/resources/statefulset.go
pkg/scheduler/frontend.go

1) Use helper Deploy() method that creates deployment task
(ConfigMap) rather than calling kubectl exec
2) Added ability to pass DependencyGraphOptions to framework methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/243)

e2e framework updates

---

pkg/scheduler/dependency_analyzer.go
pkg/scheduler/dependency_graph.go
pkg/scheduler/scheduler_test.go

Cycle detection algorithm used to detect cycles in the whole
dependency graph ignoring dependency labels and how they correspond
to flow selectors. In some cases this caused false positive result.
For example it could happen if there is a cycle between creation and
destruction flow paths even if they are not related and the deployment
succeeded.
This commit makes cycle detection flow aware. Now the cycles are
searched for each exported flow * 2 paths (construction, destruction).
The validation takes place for all known flows rather than for the one
which is we about to execute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/250)

Flow aware graph cycle detection

---

e2e/flows_test.go
pkg/interfaces/interfaces.go
pkg/resources/flow.go
pkg/scheduler/dependency_analyzer.go
pkg/scheduler/dependency_graph.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

In order to be idempotent, Create() method of the flow resource used
MinReplicaCount set to 1 and ReplicaCount set to 0. This ensured that
at least one flow replica was created and no new replicas created on
subsequent calls. If we use ReplicaCount=1 it would cause all other
replicas of the flow to be deleted. 
But this workaround is also not always correct. The problem is when
the flow has fixed replica-space. If such flow is triggered from another
flow, and say, we want to have additional N replicas of that outer flow,
all replicas of the outer flow will trigger deployment of our (inner)
flow N times, but still only 1 replica will be created.
The solution is to divide replicaspace. With this change, for each
use of the inner flow the replica object will get a composite label …

Replicaspace contexts

---

pkg/scheduler/scheduler.go

When deployment engine waits for resource to became ready,
it should use ScheduledResource.Status() rather than Status method of
the underlying resource. The difference is that for ScheduledResource,
the status may be cached or set externally. For example, this
happens when Wait() times out. Without this change, the goroutine
created by Wait() will not recognize it and will continue running and
querying resource status in endless loop until deployment ends
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/264)

Use status cache for resource readiness probes

---

pkg/client/flows.go
pkg/mocks/fake_replicas.go
pkg/resources/flow.go
pkg/scheduler/dependency_graph.go
pkg/scheduler/dependency_graph_test.go
pkg/scheduler/flows_test.go
pkg/scheduler/frontend.go
pkg/scheduler/scheduler.go

Currently, flow deployments are HA only when fixed replica count is
specified. If we run `kubeac run flow -n+2` and then the deployment
fail in the middle, after recovery it will create another 2 replicas
so we are going to get 4 new replicas instead of 2
With this change, Replica objects get additional boolean field
`Deployed` which is set to true upon replica deployment. Until then,
replica allocation algorithm will allocate replicas from previous
failed deployment (i.e. where Deployed = false) first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-appcontroller/257)

HA for relative replica count deployments

---

e2e/flows_test.go
examples/flows/create.sh
examples/flows/deps.yaml
pkg/client/flows.go
pkg/interfaces/interfaces.go
pkg/mocks/fake_replicas.go
pkg/resources/flow.go
pkg/scheduler/dependency_graph.go
pkg/scheduler/dependency_graph_test.go
pkg/scheduler/flows_test.go
pkg/scheduler/frontend.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

Currently, flow resource name is auto-generated from replica name of the
outer (consuming) graph and dependency name, whose child is the flow
resource. As a result, if we want a flow call to depend on two parent
resources, we will get two flow calls after each parent becomes ready,
rather than one call after both turn ready.
If we make flow name generation depend on replica name only, the problem
above will be solved, however it will still not be possible to have one
flow call for entire graph rather than for each replica. Also in some
cases we might want it to be called for each dependency, if there are
different arguments passed along each of them.
If we remove name generation at all, the only way, how we'll be able to
achieve behavior other, than one call per graph will be to make the …

Ability to parametrize resource key in dependency

---

e2e/flows_test.go
examples/flows/create.sh
examples/flows/deps.yaml
pkg/client/flows.go
pkg/interfaces/interfaces.go
pkg/mocks/fake_replicas.go
pkg/resources/common.go
pkg/resources/flow.go
pkg/resources/void.go
pkg/scheduler/dependency_graph.go
pkg/scheduler/dependency_graph_test.go
pkg/scheduler/flows_test.go
pkg/scheduler/frontend.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

void resource type is a resource that does nothing and is always
ready. There is no Definition for void resources, but they can be
used in dependencies by specifying "void/something" (i.e. the syntax
to refer to external resources without Definition).
Here is why it is needed:
* void resources can be used to create sync points between flow
replicas (see unit test in this commit. Similar technique is used
in etcd app, but in absence of void, service resource was used
instead)
* any vertex in the graph can be replaced by void/* without breaking
dependencies. It can be used to exclude resource from the graph and
keeping it structure
* can be used in functional tests similar to how mock resources are used
in unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" …

'void' pseudo resource type
